networks:
  pmm-net:

volumes:
  pmm-data:

services:
  percona-mysql:
    image: percona:latest
    container_name: percona-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pmm-net
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  percona-pmm-server:
    image: percona/pmm-server:2
    container_name: percona-pmm
    restart: always
    ports:
      - "8080:80"     # PMM web interface
      - "8443:443"
    networks:
      - pmm-net
    volumes:
      - pmm-data:/srv

  percona-pmm-client:
    image: percona/pmm-client:2
    container_name: pmm-client
    depends_on:
      - percona-pmm-server
      - percona-mysql
    networks:
      - pmm-net
    environment:
      PMM_AGENT_SERVER_ADDRESS: percona-pmm:443
      PMM_AGENT_SERVER_INSECURE_TLS: "1"
      PMM_AGENT_SERVER_USERNAME: admin
      PMM_AGENT_SERVER_PASSWORD: admin
      PMM_AGENT_SETUP: "1"
      PMM_AGENT_SETUP_NODE_NAME: percona-mysql-node
      PMM_AGENT_SETUP_NODE_TYPE: generic
      PMM_AGENT_SETUP_METRICS_MODE: push
    user: "0:0"
    entrypoint: >
      /bin/bash -c "sleep 20 && \
        chmod -R 777 /usr/local/percona && \
        pmm-agent setup --force --config-file=/usr/local/percona/pmm-agent.yaml && \
        pmm-admin config --server-url=https://admin:admin@percona-pmm:443 && \
        pmm-admin add mysql --force --username=root --password=root --host=percona-mysql --port=3306 --service-name=mysql-percona; exec pmm-agent --config-file=/usr/local/percona/pmm-agent.yaml"